name: rmbtc
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - notebook
  - pandas
  - numpy=1.*
  - numba
  - matplotlib=3.*
  - seaborn=0.12.*
  - scikit-learn=1.*
  - lightgbm
  - scikit-learn=1.*
  - ta-lib
